version: "3"
services:
  backend-api:
    container_name: kogda-virastu-backend
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend-mongodb
  backend-mongodb:
    image: mongo:5.0.8
    container_name: kogda-virastu-mongodb
    volumes:
      - mongo-data:/data/db
    restart: always
volumes:
  mongo-data:
    driver: local
